### ISSUE TITLE
Interface missing when using Public Network

### ISSUE THREAD

**Issue by qodeq** [pradels/vagrant-libvirt#152]
I tried to configure a public network attached to host devices.

**Config**:
```rh1501.vm.network :public_network, :dev => "eth0", :mode => 'bridge'```

**Steps**:
* (I start with no virtual networks in libvirt)
* Network vagrant-libvirt is automatically created in the net 192.168.121.0/24
* I tried this with both a real ethernet interface and a dummy interface.
   * If I use a real interface it gets stuck in ```Waiting for domain to get an IP address...```.  **Guest created does not have any network interface but loopback**.
   * If I use a dummy interface I get an error trace (see below)

**Comments**:
Is there any requirement about the state of the ethernet interface (address, up/down) before running ```vagrant up```??

Actually, my first aim would be to create my own bridges and configure vagrant-libvirt to simply attach my guests to them. I understand that this is not supported. Please correct me if I'm wrong.

**Versions**:
Host running ubuntu 13.10
libvirt-bin 1.1.1-0ubuntu8.5
vagrant 1:1.4.3
vagrant-libvirt 0.0.15

**Full trace when using dummy interface**:
```
uninitialized constant VagrantPlugins::ProviderLibvirt::Action::CreateNetworkInterfaces::NetworkNotAvailableError

/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/create_network_interfaces.rb:160:in `interface_network'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/create_network_interfaces.rb:60:in `block in call'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/create_network_interfaces.rb:39:in `each'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/create_network_interfaces.rb:39:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/create_networks.rb:76:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/provision.rb:52:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/create_domain.rb:70:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/handle_box_image.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/handle_box_url.rb:24:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/handle_storage_pool.rb:21:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/set_name_of_domain.rb:36:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/call.rb:51:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/home/user/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/connect_libvirt.rb:84:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:147:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
```

**Comment by infernix** [comment]
@qodeq @gnat42:
> Actually, my first aim would be to create my own bridges and configure vagrant-libvirt to simply attach my guests to them. I understand that this is not supported. Please correct me if I'm wrong.

In order to connect a Vagrant VM to a pre-existing bridge, use the following syntax:

```ruby
  config.vm.network "public_network", :dev => "br0", :mode => 'bridge', :type => "bridge"
```

This works fine under vagrant 1.8.1 and vagrant-libvirt 0.0.33; please reopen this issue if it is still a problem with current stable releases.
