### ISSUE TITLE
vagrant up fails after vagrant halt

### ISSUE THREAD

**Issue by jswiders** [pradels/vagrant-libvirt#293]
I've wanted to shutdown my vm for a moment so I did vagrant halt - however after that vagrant up failed with

    Name `vagrant_default` of domain about to create is already taken. Please try to run
    `vagrant up` command again.

vagrant status output:

    Current machine states:

    default                   not created (libvirt)

Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.box = "disk1"
  config.vm.network :private_network, :ip => "192.168.55.4"
  config.vm.network :private_network, :ip => "10.0.2.15"  
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.boot_timeout = 600
  config.vm.provider :libvirt do |domain|
    domain.memory = 6144
    domain.cpus = 4
    domain.nested = true
  end
end

```

and VAGRANT_LOG=info vagrant up output

```
 INFO global: Vagrant version: 1.7.1
 INFO global: Ruby version: 2.0.0
 INFO global: RubyGems version: 2.0.14
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.1/bin/vagrant"
 INFO global: VAGRANT_LOG="info"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/bin/../embedded"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_DETECTED_OS="Linux"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: Plugins:
 INFO global:   - CFPropertyList = 2.3.0
 INFO global:   - builder = 3.2.2
 INFO global:   - bundler = 1.7.9
 INFO global:   - excon = 0.43.0
 INFO global:   - fission = 0.5.0
 INFO global:   - formatador = 0.2.5
 INFO global:   - mime-types = 1.25.1
 INFO global:   - net-ssh = 2.9.2
 INFO global:   - net-scp = 1.1.2
 INFO global:   - fog-core = 1.27.2
 INFO global:   - mini_portile = 0.6.0
 INFO global:   - nokogiri = 1.6.3.1
 INFO global:   - fog-xml = 0.1.1
 INFO global:   - fog-atmos = 0.1.0
 INFO global:   - multi_json = 1.10.1
 INFO global:   - fog-json = 1.0.0
 INFO global:   - inflecto = 0.0.2
 INFO global:   - fog-brightbox = 0.7.1
 INFO global:   - fog-ecloud = 0.0.2
 INFO global:   - fog-profitbricks = 0.0.1
 INFO global:   - fog-radosgw = 0.0.3
 INFO global:   - fog-sakuracloud = 0.1.1
 INFO global:   - fog-softlayer = 0.3.30
 INFO global:   - fog-storm_on_demand = 0.1.0
 INFO global:   - fog-terremark = 0.0.3
 INFO global:   - fog-vmfusion = 0.0.1
 INFO global:   - fog-voxel = 0.0.2
 INFO global:   - ipaddress = 0.8.0
 INFO global:   - fog = 1.26.0
 INFO global:   - json = 1.8.2
 INFO global:   - rdoc = 4.2.0
 INFO global:   - rest-client = 1.6.8
 INFO global:   - ruby-libvirt = 0.5.2
 INFO global:   - vagrant-kvm = 0.2.0.dev
 INFO global:   - vagrant-libvirt = 0.0.24
 INFO global:   - vagrant-mutate = 0.3.1
 INFO global:   - vagrant-share = 1.1.4
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: CoreOS guest
 INFO manager: Registered plugin: SmartOS guest.
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: RedHat guest
 INFO manager: Registered plugin: OmniOS guest.
 INFO manager: Registered plugin: Windows guest.
 INFO manager: Registered plugin: Funtoo guest
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: NixOS guest
 INFO manager: Registered plugin: Solaris 11 guest.
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: TinyCore Linux guest.
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: Mint guest
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: Darwin guest
 INFO manager: Registered plugin: NetBSD guest
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: ESXi guest.
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: salt
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: ansible
 INFO manager: Registered plugin: file
 INFO manager: Registered plugin: shell
 INFO manager: Registered plugin: docker
 INFO manager: Registered plugin: CFEngine Provisioner
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: version command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: vagrant-login
 INFO manager: Registered plugin: help command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: push command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: rdp command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: global-status command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: list-commands command
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: heroku
 INFO manager: Registered plugin: atlas
 INFO manager: Registered plugin: local-exec
 INFO manager: Registered plugin: noop
 INFO manager: Registered plugin: ftp
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: winrm communicator
 INFO manager: Registered plugin: RSync synced folders
 INFO manager: Registered plugin: SMB synced folders
 INFO manager: Registered plugin: NFS synced folders
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: SUSE host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: Red Hat host
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: null host
 INFO manager: Registered plugin: Slackware host
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: Mac OS X host
 INFO manager: Registered plugin: Hyper-V provider
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: docker-provider
 INFO global: Loading plugins!
 INFO manager: Registered plugin: vagrant-share
 INFO manager: Registered plugin: KVM provider
 INFO manager: Registered plugin: vagrant-mutate
 INFO manager: Registered plugin: libvirt
 INFO vagrant: `vagrant` invoked: ["up"]
 INFO environment: Environment initialized (#<Vagrant::Environment:0x00000002e26970>)
 INFO environment:   - cwd: /home/altran/temp/vagrant
 INFO environment: Home path: /home/altran/.vagrant.d
 INFO environment: Local data path: /home/altran/temp/vagrant/.vagrant
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002eb6570>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000001758a90>
 INFO cli: CLI: [] "up" []
 INFO loader: Set :root = #<Pathname:/home/altran/temp/vagrant/Vagrantfile>
 INFO loader: Loading configuration in order: [:home, :root]
 INFO loader: Set "24051780_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "24051780_machine_default"]
 INFO environment: Getting machine: default (libvirt)
 INFO environment: Uncached load of machine.
 INFO loader: Set "24051780_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "24051780_machine_default"]
 INFO box_collection: Box found: disk1 (libvirt)
 INFO loader: Set :"24456080_disk1_libvirt" = #<Pathname:/home/altran/.vagrant.d/boxes/disk1/0/libvirt/Vagrantfile>
 INFO loader: Loading configuration in order: [:"24456080_disk1_libvirt", :home, :root, "24051780_machine_default"]
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: VagrantPlugins::ProviderLibvirt::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x00000002f42250>
 INFO machine:   - Data dir: /home/altran/temp/vagrant/.vagrant/machines/default/libvirt
 INFO machine: Calling action: read_state on provider Libvirt (new)
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-56ac2086f4cf77a1bbfa7b31ed254a7d
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/altran/temp/vagrant>]
 INFO host: Detected: linux!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002b2ec90>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002eb82a8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000002eb8280>
 INFO connect_libvirt: Connecting to Libvirt (qemu:///system?no_verify=1&keyfile=/home/altran/.ssh/id_rsa) ...
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000002edaf88>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000002edaf88>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000002eb8280>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002eb82a8>
 INFO environment: Released process lock: machine-action-56ac2086f4cf77a1bbfa7b31ed254a7d
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO machine: New machine ID: nil
 INFO command: With machine: default (#<VagrantPlugins::ProviderLibvirt::Provider:0x00000002c254a0 @machine=#<Vagrant::Machine: default (VagrantPlugins::ProviderLibvirt::Provider)>, @cap_logger=#<Log4r::Logger:0x00000002c47050 @fullname="vagrant::capability_host::vagrantplugins::providerlibvirt::provider", @outputters=[], @additive=true, @name="provider", @path="vagrant::capability_host::vagrantplugins::providerlibvirt", @parent=#<Log4r::Logger:0x00000001bb9ad0 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x00000001b26f00 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000001b26cf8>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x00000001b16cb8 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000001bb9850 @level=0, @outputters=[]>, @level=2, @trace=false>, @level=2, @trace=false>, @cap_host_chain=[[:libvirt, #<#<Class:0x00000002c24320>:0x00000002d1c138>]], @cap_args=[#<Vagrant::Machine: default (VagrantPlugins::ProviderLibvirt::Provider)>], @cap_caps={:hyperv=>#<Vagrant::Registry:0x00000002c47870 @items={:public_address=>#<Proc:0x0000000280bf40@/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/hyperv/plugin.rb:25>}, @results_cache={}>, :virtualbox=>#<Vagrant::Registry:0x00000002c474d8 @items={:forwarded_ports=>#<Proc:0x0000000180b6b8@/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/plugin.rb:27>, :nic_mac_addresses=>#<Proc:0x0000000180b578@/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/plugin.rb:32>, :public_address=>#<Proc:0x00000001950de8@/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share.rb:39>}, @results_cache={}>, :docker=>#<Vagrant::Registry:0x00000002c47320 @items={:public_address=>#<Proc:0x000000018bb8b0@/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/plugin.rb:54>, :proxy_machine=>#<Proc:0x000000018bb4c8@/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/plugin.rb:59>}, @results_cache={}>}>)
 INFO interface: info: Bringing machine 'default' up with 'libvirt' provider...
Bringing machine 'default' up with 'libvirt' provider...
 INFO machine: Calling action: read_state on provider Libvirt (new)
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-56ac2086f4cf77a1bbfa7b31ed254a7d
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002e6fe18>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002e732c0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000002e73298>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000002e921c0>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000002e921c0>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000002e73298>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002e732c0>
 INFO environment: Released process lock: machine-action-56ac2086f4cf77a1bbfa7b31ed254a7d
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because only executing one action
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #<Vagrant::Machine:0x0000000280b388> up {:destroy_on_error=>true, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil}
 INFO machine: Calling action: up on provider Libvirt (new)
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-56ac2086f4cf77a1bbfa7b31ed254a7d
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002edd530>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002ee8570>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000002ee84f8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x00000002f07c40>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002f3f208>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x00000002f41468>
 INFO machine: Calling action: read_state on provider Libvirt (new)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002f63cc0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002f605c0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000002f60598>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000002f7eb88>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000002f7eb88>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000002f60598>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002f605c0>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x00000002f41468>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Warden:0x00000002b1e0e8>
 INFO warden: Calling IN action: #<Proc:0x007f978452a080@/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetNameOfDomain:0x00000002b1df30>
 INFO set_name_of_domain: Looking for domain vagrant_default through list [  <Fog::Compute::Libvirt::Server
    id="ff31086c-7273-44c4-9e85-ec31627be665",
    cpus=4,
    cputime=0,
    os_type="hvm",
    memory_size=6291456,
    max_memory_size=6291456,
    name="vagrant_default",
    arch="x86_64",
    persistent=true,
    domain_type="kvm",
    uuid="ff31086c-7273-44c4-9e85-ec31627be665",
    autostart=false,
    nics=[    <Fog::Compute::Libvirt::Nic
      mac="52:54:00:2e:bb:0e",
      id=nil,
      type="network",
      network="vagrant-libvirt",
      bridge=nil,
      model="virtio"
    >,     <Fog::Compute::Libvirt::Nic
      mac="52:54:00:db:12:80",
      id=nil,
      type="network",
      network="vagrant0",
      bridge=nil,
      model="virtio"
    >,     <Fog::Compute::Libvirt::Nic
      mac="52:54:00:63:df:9f",
      id=nil,
      type="network",
      network="vagrant1",
      bridge=nil,
      model="virtio"
    >],
    volumes=[    <Fog::Compute::Libvirt::Volume
      id="/var/lib/libvirt/images/vagrant_default.img",
      pool_name="default",
      key="/var/lib/libvirt/images/vagrant_default.img",
      name="vagrant_default.img",
      path="/var/lib/libvirt/images/vagrant_default.img",
      capacity=40,
      allocation=6,
      format_type="qcow2",
      backing_volume=nil
    >],
    active=false,
    boot_order=["hd"],
    display={:type=>"vnc", :port=>"-1", :listen=>"127.0.0.1"},
    state="shutoff"
  >]
 INFO set_name_of_domain: Looking for domain vagrant_default
ERROR warden: Error occurred: Name `vagrant_default` of domain about to create is already taken. Please try to run
`vagrant up` command again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Name `vagrant_default` of domain about to create is already taken. Please try to run
`vagrant up` command again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Name `vagrant_default` of domain about to create is already taken. Please try to run
`vagrant up` command again.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000002f07c40>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-56ac2086f4cf77a1bbfa7b31ed254a7d
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002b07280>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::ProviderLibvirt::Errors::DomainNameExists: Name `vagrant_default` of domain about to create is already taken. Please try to run
`vagrant up` command again.>
ERROR vagrant: Name `vagrant_default` of domain about to create is already taken. Please try to run
`vagrant up` command again.
ERROR vagrant: /home/altran/.vagrant.d/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/set_name_of_domain.rb:30:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
/home/altran/.vagrant.d/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:212:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:189:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: Name `vagrant_default` of domain about to create is already taken. Please try to run
`vagrant up` command again.
Name `vagrant_default` of domain about to create is already taken. Please try to run
`vagrant up` command again.
 INFO interface: Machine: error-exit ["VagrantPlugins::ProviderLibvirt::Errors::DomainNameExists", "Name `vagrant_default` of domain about to create is already taken. Please try to run\n`vagrant up` command again."]
```

I've downgraded fog and fog-core to versions seen above because of issue #292 - if that can be the source of the problem.

**Comment by murdegern** [comment]
I have the same problem here. I didn't downgrade fog/fog-core, but used the mini-fix of changing Formatador.new to ::Formatador.new in fog's model.rb, so it most probably isn't the source of this problem.

**Comment by bricewge** [comment]
I just had the same issue with my domain ``packer_test_vm.xml`` so I did the this ti fix it:
```
# virsh define /etc/libvirt/qemu/packer_test_vm.xml
# virsh list --all
# virsh undefine packer_test_vm
```

**Comment by sosiouxme** [comment]
"me too"

**Comment by penguincoder** [comment]
I am experiencing this issue as well, and I have a tiny morsel of information to provide.

So when I looked in `.vagrant/machines/default/libvirt/id` file and the UUID for the created VM did not match the UUID in `virsh`. I changed it, but it still is not working. I suspect that the `.vagrant/machines/default/libvirt/index_uuid` file contains an invalid UUID to match up with Vagrant's internals, but I have no evidence to support this theory.

So if anyone else can confirm they have the same problem, that might be a lead towards the solutions. Here is a Vagrant ticket (https://github.com/mitchellh/vagrant/issues/2969) that may be related.

**Comment by sciurus** [comment]
@jswiders and or @penguincoder in this sequence

1. vagrant up (success)
1. vagrant halt
1. vagrant up (failure)

can you get me the output with VAGRANT_LOG=info for all three?

Please don't run any other commands like `vagrant status` in between those, as that can cleanup state during an error.

Regarding your info @penguincoder, I don't think index_uuid is relevant, that should only be used by vagrant's index of all VMs to map the VMs back to their environment.

Having `.vagrant/machines/default/libvirt/id` not matching the uuid you got from `virsh dumpxml` is a problem. You can see the code for determining the state of the VM is in [read_state.rb](https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/read_state.rb).

**Comment by penguincoder** [comment]
Well, I would love to help, but it has been working well since I `vagrant destroy` and `vagrant up` again.  Last night I ran a `vagrant halt` and a `vagrant up` again this morning with no ill effects. I did a `vagrant halt` and ran vagrant for a different project and brought up a different VM. I went back to the original project and did a `vagrant up` and apparently it lost all of its marbles. The `id` file was completely missing, so I recreated it using the UUID from virsh, and then did a `vagrant up` again. When it came up, vagrant assumed the machine was not provisioned (which is a lie) and rather than wait on that to finish, I destroyed it and recreated it. I will try a series of `halt` and `up` operations in a loop and see if I can get it to fail again.

**Comment by penguincoder** [comment]
It happens regularly from what I can see now. I removed some sensitive provisioning output, but that should not matter to vagrant.

vagrant up: https://gist.github.com/penguincoder/6edb33c725d00c33dcce
vagrant halt: https://gist.github.com/penguincoder/93e2ef67a1efb2779192
(there are no files in `.vagrant/machines/consolo_development/libvirt`)
vagrant up: https://gist.github.com/penguincoder/6bc9f29269ea12fdc072

**Comment by sciurus** [comment]
Thanks for this @penguincoder; I'll dig in later!

**Comment by sciurus** [comment]
I'm excluding unneeded lines from the log snippets below.

When I halt a VM, I see

```
 INFO interface: info: Halting domain...
 INFO halt_domain: Trying gracefull shutdown.
 INFO halt_domain: VM is still running. Calling force poweroff.
```

and nothing of note later. In your logs I see

```
INFO interface: info: Halting domain...
INFO halt_domain: Trying gracefull shutdown.
```

followed later by

```
INFO read_state: Machine shutting down or terminated, assuming it got destroyed.
INFO machine: New machine ID: nil
```

My feeling is that this is a bug in how we handle guests that actually properly respond to libvirt's `shutdown` command. My test guest does not, so after 30 seconds vagrant-libvirt issues the `destroy` command. I'll work on getting a guest set up that actually will shut down and on better understanding how we should track states.

As an aside, does it make me a bad person that I've been "destroying" VMs all these years :grin:

**Comment by penguincoder** [comment]
Not exactly, however, it takes me ... maybe an hour to provision my machines. I would very much prefer to not recreate them every time. I have some giant database setups to load...

**Comment by sciurus** [comment]
As a workaround, you should be able to backup your `.vagrant` directory before shutting down your machines. If after sutting them down `vagrant status` shows they are "not created", copy the backup into place and they should appear as "shutoff". I know that's a hassle but I hope it's better than having to reprovision.

I got far enough last night to know the bug isn't as bad as I first feared. Now that my test VM responds to ACPI shutdown vagrant still works. By the time I get to read_state after halt_domain my state is _shutoff_ like you would expect. For you, it seems the state is _shutting-down_ [0] which means that our check for the VM being shut down [here](https://github.com/pradels/vagrant-libvirt/blob/ac3582ae535c321d242bf3c59a7a3aff808567ee/lib/vagrant-libvirt/action/halt_domain.rb#L23) is not working correctly. I'm still working to understanding what is going on there.

[0] or possibly _destroyed_ That makes less sense but we can't distinguish between the two with the current logging. The code is [here](https://github.com/pradels/vagrant-libvirt/blob/ac3582ae535c321d242bf3c59a7a3aff808567ee/lib/vagrant-libvirt/action/read_state.rb#L31)

**Comment by penguincoder** [comment]
That's some solid spelunking. Let me know if there is anything else I can provide. The workaround will totally work for me for the time being. Something else I have been doing is manually populating the `id` file and then running `vagrant up --no-provision` which seems to mostly work.

**Comment by strzibny** [comment]
@sciurus I believe its exactly as you say. I can't confirm on 100% though because this is happening on 1 in 100 runs for me, but obviously the problem is that one loose the `machine` state that Vagrant saves for itself in `.vagrant` (and `.vagrant.d/data`). Volumes otherwise perfectly works and `ruby-libvirt` and `fog-libvirt` can read the state correctly.

**Comment by prashant0493** [comment]
I chose to have alternative domain name by editing Vagrantfile with: 
`config.vm.define "vagrant_default1" do |vagrant_default1|`
you can temporarily get away with your problem with alternative domain name until libvirt shuts down the domain.

**Comment by jniederm** [comment]
> try: `sudo vagrant undefine vagrant_default`

It's supposed to be `sudo virsh undefine vagrant_default`, right?
