### ISSUE TITLE
libvirt disk_bus parameter defaults to sata instead of virtio, and blocks the use of snapshots

### ISSUE THREAD

**Issue by varac** [pradels/vagrant-libvirt#351]
hi,

i recently got the error that i cannot do snapshots with sahara anymore, using vagrant-libvirt (which i first reported to [jedi4ever/sahara
](https://github.com/jedi4ever/sahara/issues/48):

```
--- vms/wheezy-tmp » cat Vagrantfile
Vagrant.configure(2) do |config|
  config.vm.box = "leap-wheezy"
  config.vm.box_url = "https://downloads.leap.se/platform/vagrant/libvirt/leap-wheezy.box"
end

-- vms/wheezy-tmp » vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              wheezy-tmp_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Memory:            500M
==> default:  -- Base box:          leap-wheezy
==> default:  -- Storage pool:      default
==> default:  -- Image:             /home/varac/vagrant/storagepool/wheezy-tmp_default.img
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:
==> default:  -- Initrd:
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- Command line :
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Creating shared folders metadata...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2015-04-24 15:04:21 CEST; 1h 41min ago
  Process: 1057 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 1050 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 1057 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

Apr 24 15:04:21 rocinante systemd[1]: Starting NFS server and services...
Apr 24 15:04:21 rocinante systemd[1]: Started NFS server and services.
==> default: Mounting NFS shared folders...
==> default: Configuring and enabling network interfaces...

--- vms/wheezy-tmp » vagrant ssh
Linux leap-wheezy 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Apr 23 12:50:20 2015 from 10.0.2.2
vagrant@leap-wheezy:~$ logout
Connection to 192.168.121.235 closed.

--- vms/wheezy-tmp » vagrant sandbox on
[default] Starting sandbox mode...
/home/varac/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/session/libvirt.rb:106:in `snapshot_create_xml': Call to virDomainSnapshotCreateXML failed: (Libvirt::Error) fehl: Error -22 while writing VM
  from /home/varac/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/session/libvirt.rb:106:in `on'
  from /home/varac/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/command/on.rb:28:in `block in execute'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `each'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
  from /home/varac/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/command/on.rb:19:in `execute'
  from /home/varac/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/command/root.rb:52:in `execute'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
  from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

i upgraded to ubuntu 15.04 today, but i can't tell if it is directly related. it used to work some days ago.

```
--- vms/wheezy-tmp » dpkg -l|egrep '(kvm|libvirt)'
ii  gir1.2-libvirt-glib-1.0                     0.1.9-4                                             amd64        libvirt glib mainloop integration
ii  libvirt-bin                                 1.2.12-0ubuntu12                                    amd64        programs for the libvirt library
ii  libvirt-dev                                 1.2.12-0ubuntu12                                    amd64        development files for the libvirt library
ii  libvirt-glib-1.0-0                          0.1.9-4                                             amd64        libvirt glib mainloop integration
ii  libvirt0                                    1.2.12-0ubuntu12                                    amd64        library for interfacing with different virtualization systems
ii  python-libvirt                              1.2.12-0ubuntu1                                     amd64        libvirt Python bindings
ii  qemu-kvm                                    1:2.2+dfsg-5expubuntu9                              amd64        QEMU Full virtualization
ii  ruby-libvirt                                0.5.1-3build1                                       amd64        Ruby bindings for libvirt
--- vms/wheezy-tmp » vagrant plugin list
sahara (0.0.17)
vagrant-libvirt (0.0.26)
vagrant-mutate (0.3.2)
vagrant-proxyconf (1.5.0)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)
--- vms/wheezy-tmp » vagrant --version
Vagrant 1.7.2
```

i also could not make snapshots with virsh/libvirt anymore:
```
--- vms/wheezy-tmp » virsh snapshot-create-as wheezy-tmp_default test_snap1
error: Operation schlug fehl: Error -22 while writing VM
```

it turns out that the xml config of vagrant-libvirt machines use "sata" as disk_model (instead of the default "virtio" that is documented in the README.md).

adding this to my Vagrantfile fixed the problem:

```
config.vm.provider :libvirt do |libvirt|
  libvirt.disk_bus = "virtio"
end
```

here's the diff of two running vagrant-libvirt boxes, one with the libvirt.disk_bus parameter set like above, and one without:

```
1c1
< <domain type='kvm' id='4'>
---
> <domain type='kvm' id='5'>
3c3
<   <uuid>1eb1a038-c384-4906-bfa4-72bd68929310</uuid>
---
>   <uuid>8f008e15-5192-4215-8fa3-895e1b085871</uuid>
33,35c33,35
<       <target dev='vda' bus='virtio'/>
<       <alias name='virtio-disk0'/>
<       <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
---
>       <target dev='vda' bus='sata'/>
>       <alias name='sata0-0-0'/>
>       <address type='drive' controller='0' bus='0' target='0' unit='0'/>
43a44,47
>     <controller type='sata' index='0'>
>       <alias name='sata0'/>
>       <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
>     </controller>
45c49
<       <mac address='52:54:00:24:1b:7a'/>
---
>       <mac address='52:54:00:3d:25:8e'/>
78,79c82,83
<     <label>libvirt-1eb1a038-c384-4906-bfa4-72bd68929310</label>
<     <imagelabel>libvirt-1eb1a038-c384-4906-bfa4-72bd68929310</imagelabel>
---
>     <label>libvirt-8f008e15-5192-4215-8fa3-895e1b085871</label>
>     <imagelabel>libvirt-8f008e15-5192-4215-8fa3-895e1b085871</imagelabel>

```

Please make sure that disk_model defaults to virtio again.

**Comment by pronix** [comment]
tested on fedora21 - working correct, bus is virtio.
in code also defined  virtio as default
```./lib/vagrant-libvirt/config.rb:        @disk_bus = 'virtio' if @disk_bus == UNSET_VALUE```
try to update you env or use fedora.
