### ISSUE TITLE
fog cannot be loaded in 0.0.27

### ISSUE THREAD

**Issue by babilen** [pradels/vagrant-libvirt#363]
Hello,

I updated `vagrant-libvirt` to 0.0.27 this morning and am now greeted with:

```
/home/babilen/.vagrant.d/gems/gems/vagrant-libvirt-0.0.27/lib/vagrant-libvirt/action/connect_libvirt.rb:1:in `require': cannot load such file -- fog (LoadError)
	from /home/babilen/.vagrant.d/gems/gems/vagrant-libvirt-0.0.27/lib/vagrant-libvirt/action/connect_libvirt.rb:1:in `<top (required)>'
	from /home/babilen/.vagrant.d/gems/gems/vagrant-libvirt-0.0.27/lib/vagrant-libvirt/action.rb:273:in `block in action_read_state'
	from /home/babilen/.vagrant.d/gems/gems/vagrant-libvirt-0.0.27/lib/vagrant-libvirt/action.rb:271:in `tap'
	from /home/babilen/.vagrant.d/gems/gems/vagrant-libvirt-0.0.27/lib/vagrant-libvirt/action.rb:271:in `action_read_state'
	from /home/babilen/.vagrant.d/gems/gems/vagrant-libvirt-0.0.27/lib/vagrant-libvirt/provider.rb:21:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:180:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /home/wwentland/.vagrant.d/gems/gems/vagrant-libvirt-0.0.27/lib/vagrant-libvirt/provider.rb:70:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:480:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:141:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:614:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:201:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:200:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:200:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/status/command.rb:20:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

This might be due to 749b431bc85a6a94dbda77e95e5e005b335953a7, but I can't be sure of that as `~/.vagrant.d/gems/gems/fog-libvirt-0.0.1` can be found on the system.

I believe that https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/connect_libvirt.rb#L1 should be `require 'fog/libvirt'` rather than `require 'fog'`.Could that be the case?

**Comment by jorgemoralespou** [comment]
I'm facing same issue, since update. :-(

**Comment by johnmccabe** [comment]
Same problem here. Manually updating connect_libvirt.rb as @babilen suggests gets it working again for me.

**Comment by pronix** [comment]
thanks. fix added.
