### ISSUE TITLE
action/destroy_domain.rb:42:in `block in call': undefined method `destroy' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by mkerrin** [pradels/vagrant-libvirt#364]
We have a Vagrant environment that sets up 7 VM's and another environment that sets up 1 VM.
When I try and destroy the 7 node environment I get the following error at some point during the destruction. Sometimes after 3 nodes sometimes after the 5th.
```
/home/jenkins/.vagrant.d/gems/gems/vagrant-libvirt-0.0.28/lib/vagrant-libvirt/action/destroy_domain.rb:42:in `block in call': undefined method `destroy' for nil:NilClass (NoMethodError)
        from /home/jenkins/.vagrant.d/gems/gems/vagrant-libvirt-0.0.28/lib/vagrant-libvirt/action/destroy_domain.rb:38:in `each'
        from /home/jenkins/.vagrant.d/gems/gems/vagrant-libvirt-0.0.28/lib/vagrant-libvirt/action/destroy_domain.rb:38:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /home/jenkins/.vagrant.d/gems/gems/vagrant-libvirt-0.0.28/lib/vagrant-libvirt/action/forward_ports.rb:193:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /home/jenkins/.vagrant.d/gems/gems/vagrant-libvirt-0.0.28/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/destroy/command.rb:31:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/destroy/command.rb:30:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

For the nodes that were deleted I can see that the volumes associated with them have been deleted.

**Comment by mkerrin** [comment]
Of the 7 nodes, 6 have 2 disks attached to them and one has none. The failure seems to happen with the  nodes with 2 disks form what I have seen

**Comment by pronix** [comment]
Thanks for report. I have some ideas, will fix evening.

**Comment by mkerrin** [comment]
Great thanks

**Comment by pronix** [comment]
show your vagrantfile please

**Comment by SimonPe** [comment]
@mkerrin : did you manually set :path on any of your disks? if so #365 should be the fix you are looking for.

**Comment by mkerrin** [comment]
Thanks for fixing this - this worked great.

@SimonPe no I wasn't setting the :path on the disks.
