### ISSUE TITLE
Self made CentOS 6.6 Box: prepare_nfs_settings.rb:44 gives Array instead of String

### ISSUE THREAD

**Issue by aalba6675** [pradels/vagrant-libvirt#401]
1. I made my own box from http://cloud.centos.org/centos/6.6/images/CentOS-6-x86_64-GenericCloud.qcow2 (very minimal VM image) by adding the vagrant user/sudo etc.
On Ubuntu host /v0.0.30 prepare_nfs_settings.rb:44 returns an Array (single element array with ip[0]) being the IP address) instead of String.

For metadata.json / VagrantFile I am reusing the contents from the official CentOS 7 box
http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-Vagrant-1505-x86_64-01.LibVirt.box

metadata.json
{"provider": "libvirt", "format": "qcow2", "virtual_size": 11}

VagrantFile
Vagrant.configure('2') do |config|
        config.vm.synced_folder ".", "/home/vagrant/sync", type: "rsync"
        config.vm.provider :libvirt do |libvirt|
                libvirt.driver = 'kvm'
                libvirt.connect_via_ssh = false
                libvirt.username = 'root'
                libvirt.storage_pool_name = 'default'
        end
end

Could someone help to explain how this variable is derived so I can debug why it is returning an Array in my box? Is there some sort or parsing (e.g. via dnsmasq leases on the host, or "ip addr/ifconfig"  guess work on the guest). SSH works, and sync folder with rsync works too - so the client IP address doesn't seem to be an issue. Oddly, the value of ip[0] is the correct guest address (192.168.121.x)  instead of being garbage, so if I test for   ip.is_array and return ip[0]  NFS sync folders work!

I just cannot figure out why this homebrew box is returing an  Array at this code.

2. The exact same box on 0.0.26/Fedora 22 works, so it doesn't seem to be a box/CentOS 6.6 issue.

3. With Ubuntu/v0.0.30, a mutated chef/centos-6.6 box works too and I can't really see any difference between the contents of chef/centos-6.6 and my home brew.
I have compared  /etc/sysconfig/network* in both boxes and they are the same.

**Comment by anduslim** [comment]
Hi,

I am also experiencing the same error with the cloud centos 6.6 image. Below is the log output from `VAGRANT_LOG=INFO vagrant up --provider=libvirt`:

```
==> default: Configuring and enabling network interfaces...
 INFO ssh: SSH is ready!
 INFO ssh: Execute:  (sudo=false)
 INFO guest: Execute capability: configure_networks [#<Vagrant::Machine: default (VagrantPlugins::ProviderLibvirt::Provider)>, []] (redhat)
 INFO ssh: SSH is ready!
 INFO ssh: Execute:  (sudo=false)
 INFO guest: Execute capability: flavor [#<Vagrant::Machine: default (VagrantPlugins::ProviderLibvirt::Provider)>] (redhat)
 INFO ssh: Execute: cat /etc/redhat-release (sudo=true)
 INFO ssh: SSH is ready!
 INFO ssh: Execute:  (sudo=false)
 INFO guest: Execute capability: network_scripts_dir [#<Vagrant::Machine: default (VagrantPlugins::ProviderLibvirt::Provider)>] (redhat)
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworkInterfaces:0x00000003ff64e8>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworks:0x00000003fbf740>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ShareFolders:0x00000003f88560>
 INFO host: Execute capability: nfs_installed [#<Vagrant::Environment: /home/andus/code/ansible-examples/centos-clean-libvirt/vm2>] (linux)
 INFO nfs: Using NFS, preparing NFS settings by reading host IP and machine IP
 INFO machine: Calling action: read_ssh_info on provider Libvirt (7d193a0d-8440-4386-8700-ad8521b133f3)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000004140ad8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000023e37d8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x000000023e35d0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ReadSSHInfo:0x00000002cd1520>
 INFO machine: Calling action: read_state on provider Libvirt (7d193a0d-8440-4386-8700-ad8521b133f3)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000003400058>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003408820>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x000000034085c8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000003461e98>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000003461e98>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x000000034085c8>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003408820>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ReadSSHInfo:0x00000002cd1520>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x000000023e35d0>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000023e37d8>
 INFO ssh: Execute: ip addr show | grep -i 'inet ' | grep -v '127.0.0.1' | tr -s ' ' | cut -d' ' -f3 | cut -d'/' -f 1 (sudo=false)
 INFO nfs: guest IPs: 192.168.121.22
ERROR warden: Error occurred: no implicit conversion of Array into String
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x000000027d4e00>
 INFO machine: Calling action: read_state on provider Libvirt (7d193a0d-8440-4386-8700-ad8521b133f3)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000003e7fb78>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003e86ab8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000003e86a68>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000003ec6a28>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x00000003ec6a28>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000003e86a68>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003e86ab8>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x0000000270e5c0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002798b30>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x000000027986d0>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000000033941c8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x0000000339d2c8>
 INFO machine: Calling action: read_state on provider Libvirt (7d193a0d-8440-4386-8700-ad8521b133f3)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x0000000340c470>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003416218>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x000000034161c8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x0000000346f408>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ReadState:0x0000000346f408>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x000000034161c8>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003416218>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x0000000339d2c8>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Warden:0x00000003d276b8>
 INFO warden: Calling IN action: #<Proc:0x00000003f97768@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000003d27528>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ClearForwardedPorts:0x00000003e737d8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::DestroyDomain:0x00000003ebacf0>
 INFO interface: info: Removing domain...
 INFO interface: info: ==> default: Removing domain...
==> default: Removing domain...
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::DestroyNetworks:0x00000003eebf08>
 INFO machine: New machine ID: nil
 INFO warden: Calling IN action: #<Proc:0x00000003f21c20@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<Proc:0x00000003f21c20@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::DestroyNetworks:0x00000003eebf08>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::DestroyDomain:0x00000003ebacf0>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ClearForwardedPorts:0x00000003e737d8>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ConnectLibvirt:0x00000003d27528>
 INFO warden: Calling OUT action: #<Proc:0x00000003f97768@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::Call:0x000000027986d0>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002798b30>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: no implicit conversion of Array into String
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: no implicit conversion of Array into String
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000003eedbf0>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-92d1281a4f58b1a33e60f5357a141ab8
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002ae9208>
/home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:44:in `connect': no implicit conversion of Array into String (TypeError)
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:44:in `block in read_host_ip'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:43:in `open'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:43:in `read_host_ip'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:23:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/create_domain.rb:169:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:42:in `block in call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `synchronize'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:24:in `block in call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `synchronize'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/andus/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

I printed out the ip before line 44 in prepare_nfs_settings.rb. Here is what i get `["192.168.121.169"]`. 

Hope this helps

**Comment by cuky23** [comment]
I am getting this error posting undertaking a new install of vagrant plug-in 

prepare_nfs_settings.rb:44:in `connect': no implicit conversion of Array into String (TypeError)

Also a bad feature was, that vagrant reload <VMNAME> instead of reloading, it actually removed the VM.

My Centos7.1 install of vagrant is now totally broken big issues with vagrant-libvirt-0.0.30

**Comment by cuky23** [comment]
I have found the following seems to get a working install on Centos7

vagrant plugin install --plugin-version 1.6.3.1 nokogiri
vagrant plugin install --plugin-version 0.4 ruby-libvirt
vagrant plugin install --plugin-version 1.16.0 fog
vagrant plugin install --plugin-version 0.0.24 vagrant-libvirt

vagrant-libvirt-0.0.30 : defo broken with "prepare_nfs_settings.rb:44:in `connect': no implicit conversion of Array into String (TypeError)" please FIX

**Comment by indiv0** [comment]
+1 getting the same issue trying to install CoreOS on libvirt with vagrant-libvirt.

**Comment by stephencooke** [comment]
Seems to still be broken, I have just done a reinstall using vagrant-1.7.4-1.x86_64

vagrant plugin  list
nokogiri (1.6.3.1)
fog (1.34.0)
ruby-libvirt (0.5.2)
vagrant-libvirt (0.0.30)
vagrant-share (1.1.4, system)

prepare_nfs_settings.rb:44:in `connect': no implicit conversion of Array into String (TypeError)

I have uninstalled the latest plugins and installed the versions detailed above and these work with the latest rpm.

**Comment by electrofelix** [comment]
Did you try building the vagrant-libvirt gem from git? As there hasn't been a release since the fix landed.

**Comment by stephencooke** [comment]
A colleague and I did chat about this, as we are running production equipment we dont want to use anything that hasnt been TAGGED and released.   

so can we have a new release soon please.

**Comment by infernix** [comment]
I'm closing this in lieu of #572 and #544, it's pretty clear that the NFS mount code needs some rewriting as there are a number of problems, but i'd like to keep it to one issue.
