### ISSUE TITLE
unable to install boxes from hashicorp

### ISSUE THREAD

**Issue by moozer** [pradels/vagrant-libvirt#431]
When I install a libvirt box from hashicorp (vagrant's default location), the base image is not copied to /var/lib/libvirt/images. "Vagrant up" then fails, since it is missing the base image in /var/lib/libvirt/images.
See below for output.

The way I read the output, adding a box does not include copying the base image to the storage pool.

It seems to be a bug. 
Am I doing something wrong?

---
Debug output
---
mon@monacer:~/git/test$ vagrant box add naelyn/ubuntu-trusty64-libvirt --debug
....
DEBUG box_collection: Box directory: /home/mon/.vagrant.d/boxes/naelyn-VAGRANTSLASH-ubuntu-trusty64-libvirt/14.04
DEBUG box_collection: Moving: /home/mon/.vagrant.d/tmp/vagrant-box-add-temp-20150728-11972-rfwz35/metadata.json => /home/mon/.vagrant.d/boxes/naelyn-VAGRANTSLASH-ubuntu-trusty64-libvirt/14.04/libvirt/metadata.json
DEBUG box_collection: Moving: /home/mon/.vagrant.d/tmp/vagrant-box-add-temp-20150728-11972-rfwz35/Vagrantfile => /home/mon/.vagrant.d/boxes/naelyn-VAGRANTSLASH-ubuntu-trusty64-libvirt/14.04/libvirt/Vagrantfile
DEBUG box_collection: Moving: /home/mon/.vagrant.d/tmp/vagrant-box-add-temp-20150728-11972-rfwz35/box.img => /home/mon/.vagrant.d/boxes/naelyn-VAGRANTSLASH-ubuntu-trusty64-libvirt/14.04/libvirt/box.img
...
 INFO interface: success: ==> box: Successfully added box 'naelyn/ubuntu-trusty64-libvirt' (v14.04) for 'libvirt'!
==> box: Successfully added box 'naelyn/ubuntu-trusty64-libvirt' (v14.04) for 'libvirt'!
...

mon@monacer:~/git/test$ vagrant init naelyn/ubuntu-trusty64-libvirt
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
mon@monacer:~/git/test$ vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
/home/mon/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/list_volumes.rb:32:in `info': Call to virStorageVolGetInfo failed: Storage volume not found: no storage vol with matching path '/var/lib/libvirt/images/moozer-VAGRANTSLASH-base-ob57_vagrant_box_image_0.0.1.img' (Libvirt::RetrieveError)
	from /home/mon/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/list_volumes.rb:32:in `volume_to_attributes'
	from /home/mon/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/list_volumes.rb:10:in `block (2 levels) in list_volumes'
	from /home/mon/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/list_volumes.rb:9:in `each'
...

**Comment by moozer** [comment]
Ok
I found the problem. It was a variation on the theme of #85

As part of my development I had removes the box, and the base file, but has not done the "pool-refresh".
