### ISSUE TITLE
vagrant up: Broken XML is generated

### ISSUE THREAD

**Issue by yanosz** [pradels/vagrant-libvirt#454]
Error:

```
$ vagrant up
Bringing machine 'test_vm' up with 'libvirt' provider...
==> test_vm: Uploading base box image as volume into libvirt storage...

/root/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb:7:in `create_volume_xml': Call to virNetworkCreateXML failed: invalid argument: unknown suffix '.0G' (Libvirt::Error)
        from /root/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb:7:in `create_volume'
        from /root/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/models/compute/volume.rb:40:in `save'
        from /root/.vagrant.d/gems/gems/fog-core-1.32.1/lib/fog/core/collection.rb:51:in `create'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:56:in `block in call'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `synchronize'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:24:in `block in call'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `synchronize'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

When outputting the xml in 
/root/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb there is:
```
<volume>
        <name>jessie-template_vagrant_box_image_0.img</name>
        <allocation unit="M">8193</allocation>
        <capacity unit=".0G">8</capacity>
        <target>
          <format type="qcow2"/>
          <permissions>
            <owner>0</owner>
            <group>0</group>
            <mode>0744</mode>
            <label>virt_image_t</label>
          </permissions>
        </target>
        </volume>
```
This is broken, since .0G is not a valid unit.
System is Debian 8 - Ruby is ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

**Comment by pronix** [comment]
By default this is specified in bytes, but an optional attribute unit can be specified to adjust the passed value. Values can be: 'B' or 'bytes' for bytes, 'KB' (kilobytes, 103 or 1000 bytes), 'K' or 'KiB' (kibibytes, 210 or 1024 bytes), 'MB' (megabytes, 106 or 1,000,000 bytes), 'M' or 'MiB' (mebibytes, 220 or 1,048,576 bytes), 'GB' (gigabytes, 109 or 1,000,000,000 bytes), 'G' or 'GiB' (gibibytes, 230 or 1,073,741,824 bytes), 'TB' (terabytes, 1012 or 1,000,000,000,000 bytes), 'T' or 'TiB' (tebibytes, 240 or 1,099,511,627,776 bytes), 'PB' (petabytes, 1015 or 1,000,000,000,000,000 bytes), 'P' or 'PiB' (pebibytes, 250 or 1,125,899,906,842,624 bytes), 'EB' (exabytes, 1018 or 1,000,000,000,000,000,000 bytes), or 'E' or 'EiB' (exbibytes, 260 or 1,152,921,504,606,846,976 bytes)

https://libvirt.org/formatstorage.html

**Comment by yanosz** [comment]
thanks for your feedback - but why do you close this issue? From my understanding vagrant-libvirt is generating invalid XML... why do you think, that this is not an issue?

**Comment by yanosz** [comment]
Debugging futher:
The box is generate by tools/create_box.sh - metadata is: 
```
{
    "provider": "libvirt",
    "format": "qcow2",
    "virtual_size": 8.0
}
```
Looking at 8.0, .0 is evaluated as the unit. This happens, because 8.0 (as a floating-point number) is passed to fog-libvirt (fog-libvirt-0.0.2/lib/fog/libvirt/models/compute/volume.rb  - Look at line 112 we have

```
        def split_size_unit(text)
          if text.kind_of? Integer
            # if text is an integer, match will fail
            size    = text
            unit    = 'G'
          else
            matcher = text.match(/(\d+)(.+)/)
            size    = matcher[1]
            unit    = matcher[2]
          end
          [size, unit]
        end
```
As a consequence, floating point numbers should not be passed to fog-libvirt-0.0.2.
Thus, we can either patch fog-libvirt-0.0.2 to handle floating point numbers or we can patch vagrant-libvirt to not pass floating point numbers.
Anyway, I don't think that closing this issue helps :-/

**Comment by pirogoeth** [comment]
Was there ever a solution for this? @yanosz @pronix
