### ISSUE TITLE
Doesn't work well with remote server

### ISSUE THREAD

**Issue by romu70** [pradels/vagrant-libvirt#522]
I've setup a VMs server and I'm trying to drive it remotely with vagrant-libvirt. 
I first downloaded the default Ubuntu server vagrant image, and converted it from VirtualBox to LibVirt with ```vagrant mutate```.

Then, I wrote this vagrantfile:

```
  config.vm.box = "trusty64" 
  config.vm.define "trusty64" do |the|
    the.vm.hostname = "trusty64"
    
    the.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.memory = 1024
        libvirt.storage_pool_name = "vmsi"
        libvirt.disk_bus = "ide"
        libvirt.host = "<ip>"
        libvirt.username = "romu"
        libvirt.connect_via_ssh = true     # also needed
    end
  end
```

If I run this script, slightly modified, locally, it works flawlessly. But if I run it on my remote server, I see the VM starts...and then closes. Here is the trace:

```
==> trusty64: Setting hostname...
==> trusty64: Configuring and enabling network interfaces...
==> trusty64: Removing domain...
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:44:in `connect': no implicit conversion of Array into String (TypeError)
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:44:in `block in read_host_ip'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:43:in `open'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:43:in `read_host_ip'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:23:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/create_domain.rb:169:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:42:in `block in call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `synchronize'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:24:in `block in call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `synchronize'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/lib/vagrant/machine.rb:214:in `action_raw'
	from /usr/share/vagrant/lib/vagrant/machine.rb:191:in `block in action'
	from /usr/share/vagrant/lib/vagrant/environment.rb:516:in `lock'
	from /usr/share/vagrant/lib/vagrant/machine.rb:178:in `call'
	from /usr/share/vagrant/lib/vagrant/machine.rb:178:in `action'
	from /usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

Any idea? Thanks.

**Comment by pronix** [comment]
try to use master branch

**Comment by romu70** [comment]
You're right, it's installed from the RPMs provided by the Fedora repositories. My first thought was to install it as described here, but it failed because of some errors building ruby-libvirt. I'll re-try, and I'll post the errors I get.

**Comment by romu70** [comment]
Indeed, the problem I have to install the master branch are exactly the ones described in #290. Except I'm running Fedora 23.

**Comment by romu70** [comment]
I've removed all packages previously installed from DNF. Installed Vagrant 1.7.4 from the Vagrant web site. Now, the installation of the vagrant-libvirt plugin fails on json.

```
gem install json -v '1.8.3'
Fetching: json-1.8.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20151208-4725-uvxrwl.rb extconf.rb
creating Makefile

make "DESTDIR=" clean
rm -f 
rm -f generator.so  *.o  *.bak mkmf.log .*.time

make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -DJSON_GENERATOR    -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC -m64 -o generator.o -c generator.c
make: gcc: Command not found
Makefile:238: recipe for target 'generator.o' failed
make: *** [generator.o] Error 127

make failed, exit code 2

Gem files will remain installed in /home/romuald/.gem/ruby/gems/json-1.8.3 for inspection.
Results logged to /home/romuald/.gem/ruby/extensions/x86_64-linux/json-1.8.3/gem_make.out
```

**Comment by romu70** [comment]
Any help on this issue, please? Because right now, if I'm not able to manage VMs remotely, that's a showstopper to me.

**Comment by pronix** [comment]
If something not working - fix it.

**Comment by romu70** [comment]
That's really useful answer thanks.

**Comment by romu70** [comment]
So, you kicked my ass, and you were right to do so! Thanks. I now run vagrant-libvirt 0.0.32 and this issue is gone. Great!
