### ISSUE TITLE
Bridge name conflict issue

### ISSUE THREAD

**Issue by elemoine** [pradels/vagrant-libvirt#530]
This is what my Vagrantfile includes:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "public_network", dev: "virbr0", mode: "bridge", type: "bridge"
  # …
```

With this `vagrant up` fails with this libvirt-vagrant error:

```
/home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:58:in `read_machine_ip': undefined method `[]' for nil:NilClass (NoMethodError)
```

The full error output is provided at the end of the issue description.

If I edit my Vagrantfile and change "virbr0" to "virbr1" in the "public_network" definition, then things work as expected: `vagrant up` succeeds and I can `vagrant ssh` into the guest.

It seems to me that the problem is related to "virbr0" being used for the management network created by vagrant-libvirt, but I am not sure.

Is this problem known?

Thanks.

----
Full error output:
```
[elemoine vagrant (master u=)]$ vagrant up
Bringing machine 'operator' up with 'libvirt' provider...
==> operator: Creating image (snapshot of base box volume).
==> operator: Creating domain with the following settings...
==> operator:  -- Name:              vagrant_operator
==> operator:  -- Domain type:       kvm
==> operator:  -- Cpus:              4
==> operator:  -- Memory:            4096M
==> operator:  -- Management MAC:    
==> operator:  -- Loader:            
==> operator:  -- Base box:          centos/7
==> operator:  -- Storage pool:      default
==> operator:  -- Image:             /var/lib/libvirt/images/vagrant_operator.img (41G)
==> operator:  -- Volume Cache:      default
==> operator:  -- Kernel:            
==> operator:  -- Initrd:            
==> operator:  -- Graphics Type:     vnc
==> operator:  -- Graphics Port:     5900
==> operator:  -- Graphics IP:       127.0.0.1
==> operator:  -- Graphics Password: Not defined
==> operator:  -- Video Type:        cirrus
==> operator:  -- Video VRAM:        9216
==> operator:  -- Keymap:            en-us
==> operator:  -- INPUT:             type=mouse, bus=ps2
==> operator:  -- Command line : 
==> operator: Creating shared folders metadata...
==> operator: Starting domain.
==> operator: Waiting for domain to get an IP address...
==> operator: Waiting for SSH to become available...
    operator: 
    operator: Vagrant insecure key detected. Vagrant will automatically replace
    operator: this with a newly generated keypair for better security.
    operator: 
    operator: Inserting generated public key within guest...
    operator: Removing insecure key from the guest if its present...
    operator: Key inserted! Disconnecting and reconnecting using new SSH key...
==> operator: Setting hostname...
==> operator: Configuring and enabling network interfaces...
==> operator: Removing domain...
==> operator: Running cleanup tasks for 'shell' provisioner...
==> operator: Running cleanup tasks for 'shell' provisioner...
/home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:58:in `read_machine_ip': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:22:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /home/elemoine/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/action/update_all.rb:27:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_domain.rb:201:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_box_image.rb:109:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /home/elemoine/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:212:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:189:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:176:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:176:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by infernix** [comment]
I've tried to reproduce it in various ways by attaching the `public_network` bridge to the same bridge as the `private_network` but I did not succeed. 

Can you upgrade to the latest version of Vagrant (1.8.1) and the vagrant-libvirt plugin and retry?

If the problem persists, can you additionally paste the output of `ip addr`, `brctl show`, `virsh net-list` and a`virsh net-dumpxml foo`, replacing `foo` with each of the listed libvirt networks?

**Comment by elemoine** [comment]
I'll try to reproduce this. In the mean time, I think you can close this issue. I'll reopen it if I see the problem again. Thanks for getting back to me.

**Comment by infernix** [comment]
:+1:
