### ISSUE TITLE
Vagrant-libvirt should break install for vagrant < 1.5.0

### ISSUE THREAD

**Issue by skywalkerd** [pradels/vagrant-libvirt#586]
When I type `vagrant init rboyer/ubuntu-trusty64-libvirt`, I've got that error message:

```
Failed to load the "vagrant-libvirt" plugin. View logs for more details.
```

When I do `vagrant init rboyer/ubuntu-trusty64-libvirt --debug &> debug.log`, here is what the log shows up:

```
ERROR root: Failed to load plugin: vagrant-libvirt
ERROR root:  -- Error: #<SyntaxError: /home/ajacques/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/plugin.rb:14: constant re-assignment>
ERROR root:  -- Backtrace:
ERROR root: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/ajacques/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt.rb:17:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
/usr/lib/ruby/vendor_ruby/vagrant.rb:204:in `require_plugin'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:760:in `block in load_plugins'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:751:in `each'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:751:in `load_plugins'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:132:in `initialize'
/usr/bin/vagrant:105:in `new'
/usr/bin/vagrant:105:in `<main>'
 INFO interface: error: Failed to load the "vagrant-libvirt" plugin. View logs for more details.

Failed to load the "vagrant-libvirt" plugin. View logs for more details.
```

I'm on Ubuntu 14.04.4, vagrant 1.4.3 and libvirt 1.2.2

**Comment by infernix** [comment]
Vagrant 1.4.3 is rather old, can you please test with 1.8.1?

**Comment by infernix** [comment]
Actually the answer is simple, vagrant > 1.5 is required.  But I'm not sure why vagrant 1.4.3 even completes installation:

```ruby
# This is a sanity check to make sure no one is attempting to install
# this into an early Vagrant version.
if Vagrant::VERSION < '1.5.0'
  raise 'The Vagrant Libvirt plugin is only compatible with Vagrant 1.5+'
end
```

Seems like this isn't working with vagrant 1.4.3 in Ubuntu. Need to investigate.

**Comment by skywalkerd** [comment]
Just letting you know that after upgrading to vagrant 1.8, adding some packages (something about ruby-libvirt not being install or something), I manage to make vagrant-libvirt work.
